fn main() {
    let a = 5832;
    let b = 9167;
    let nan = 0/0;
    let inf = 1/0;
    let big = 999999999999;

    // unary
    assert_eq_num(-a, -5832);
    assert_eq_num(!a, -5833);
    
    // integer conversions
    {
        assert_eq_num(!!2.9, 2);
        assert_eq_num(!!-2.9, -2);
        assert_eq_num(!!a, a);
        assert_eq_num(!!b, b);
        assert_eq_num(!!-a, -a);
        assert_eq_num(!!-b, -b);
        assert_eq_num(!!nan, 0);
        assert_eq_num(!!-nan, 0);
        assert_eq_num(!!inf, 2147483647);
        assert_eq_num(!!-inf, -2147483648);
        assert_eq_num(!!big, 2147483647);
        assert_eq_num(!!-big, -2147483648);
    }

    assert_eq_num(a + b, 14999);
    assert_eq_num(a - b, -3335);
    assert_eq_num(a * b, 53461944);
    assert_eq_num(a / b, 0.6361950474528199);

    // TRUNCATED division
    assert_eq_num(b % a, 3335);
    assert_eq_num(-b % a, -3335);
    assert_eq_num(b % -a, 3335);
    assert_eq_num(-b % -a, -3335);

    // bitwise
    assert_eq_num(a | b, 14287);
    assert_eq_num(a & b, 712);
    assert_eq_num(a ^ b, 13575);
    
    assert_eq_num(a << 4, 93312);
    assert_eq_num(-a << 4, -93312);
    assert_eq_num(a >> 4, 364);
    assert_eq_num(-a >> 4, -365);
    assert_eq_num(a >>> 4, 364);
    assert_eq_num(-a >>> 4, 268435091);

    // COMPARISONS
    assert_eq_bool(a == b, false);
    assert_eq_bool(b == a, false);
    assert_eq_bool(a == a, true);

    assert_eq_bool(a != b, true);
    assert_eq_bool(b != a, true);
    assert_eq_bool(a != a, false);

    assert_eq_bool(a > b, false);
    assert_eq_bool(b > a, true);
    assert_eq_bool(a > a, false);

    assert_eq_bool(a < b, true);
    assert_eq_bool(b < a, false);
    assert_eq_bool(a < a, false);

    assert_eq_bool(a >= b, false);
    assert_eq_bool(b >= a, true);
    assert_eq_bool(a >= a, true);

    assert_eq_bool(a <= b, true);
    assert_eq_bool(b <= a, false);
    assert_eq_bool(a <= a, true);

    assert_eq_bool(inf == inf, true);
    assert_eq_bool(inf != inf, false);
    assert_eq_bool(nan == nan, false);
    assert_eq_bool(nan != nan, true);
}
