[package]
name = "buntscript-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.50", features = ["full"] }
quote = "1.0.35"
proc-macro2 = "1.0.78"
